ToDoList/ToDoList/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Data;
using ToDoList.Models;
using ToDoList.ViewModels;

namespace ToDoList.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;


        public DashboardController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
                                    SignInManager<ApplicationUser> signInManager)

        {

            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;

        }
        public async Task<IActionResult> Index()
        {
            var loggedInUser = await _userManager.GetUserAsync(User);
            var vm = new UserVM()
            {
                Id = loggedInUser.Id,
                FirstName = loggedInUser.FirstName,
                LastName = loggedInUser.LastName,
                Username = loggedInUser.UserName,
                Email = loggedInUser.Email,
                RegisterDate = loggedInUser.RegisterDate,
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAccount()
        {
            var loggedInUser = await _userManager.GetUserAsync(User);
            var result = await _userManager.DeleteAsync(loggedInUser);

            if (result.Succeeded)
            {
                TempData["SuccessMessage"] = "Your account has been succesfully deleted";
                await _signInManager.SignOutAsync();
                return RedirectToAction("Home","Pages");
            }
            return View();

        }
    }
}

ToDoList/ToDoList/Controllers/PagesController.cs
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using ToDoList.Models;
using ToDoList.Services;
using ToDoList.ViewModels;

namespace ToDoList.Controllers
{
    public class PagesController : Controller
    {
        private readonly ILogger<PagesController> _logger;
        private readonly IEmailSender _emailSender;

        public PagesController(ILogger<PagesController> logger, IEmailSender emailSender)
        {
            _logger = logger;
            _emailSender = emailSender;
        }

        public IActionResult Home()
        {
            return View();
        }


        public IActionResult Contact()
        {
           
            return View();
        }

        [HttpGet("/accessdenied")]
        public IActionResult AccessDenied()
        {

            return View();
        }

        [HttpPost]
        public IActionResult SendMessage(ContactFormVM vm)
        {
           
            if (!ModelState.IsValid)
            {
                return View("Contact");
            }
            try
            {
                _emailSender.SendEmailAsync(vm.Name, vm.Email, vm.Subject, vm.Message);
                TempData["MessageStatus"] = "Message sent successfully";
            }
            catch
            {
                TempData["MessageStatus"] = "Message sending failed";
            }
           

            return RedirectToAction("Contact",vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoList/ToDoList/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoList.Data;
using ToDoList.Models;
using ToDoList.ViewModels;

namespace ToDoList.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string search)
        {
            var users = new List<ApplicationUser>();
            if (search != null)
            {
                 users = await _context.Users.Where(x => x.Email != "orxanm385@gmail.com").Where(x => x.EmailConfirmed && x.FirstName.Contains(search)).ToListAsync();

            }
            else
            {
                 users = await _context.Users.Where(x => x.Email != "orxanm385@gmail.com").Where(x => x.EmailConfirmed).ToListAsync();

            }

            var vm = users.Select(x => new UserVM
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                RegisterDate = x.RegisterDate,
                Username = x.UserName,
                Email = x.Email,
            }).ToList();
            return View(vm);
        }
    }
}

ToDoList/ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - ToDoList</title>


    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Topbar Navbar -->

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" style="color: black;" asp-controller="Pages" asp-action="Home">Home</a>
                            </li>
                            
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="ToDos" asp-action="Index" style="color: black;">My To Do List</a>
                                </li>

                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Users" asp-action="Index" style="color: black;">Users</a>
                                    </li>
                                }
                            }
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Pages" asp-action="Contact" style="color: black;">Contact</a>
                            </li>

                        </ul>

                        <ul class="navbar-nav ml-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" style="color: black;" asp-controller="Accounts" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: black;" asp-controller="Accounts" asp-action="Register">Register</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" style="color: black;" asp-action="Index" asp-controller="Dashboard">@User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color: black;" asp-controller="Accounts" asp-action="LogOut">Log out</a>
                                </li>
                            }

                        </ul>


                    </div>


                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>To Do List</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/js/demo/chart-area-demo.js"></script>
    <script src="~/js/demo/chart-pie-demo.js"></script>
    <script src="~/js/demo/chart-bar-demo.js"></script>
    <script>


        $("#IsCompleted").on("change", function () {
            alert("click");
        });

    </script>
    

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>